In [91]:
import pandas as pd


In [3]:
counter=0
while counter <12:
    print (counter)
    counter =counter+1
print('hello')


0
1
2
3
4
5
6
7
8
9
10
11
hello


In [6]:
for i in range(5):
    print('I is equal to:',i)

I is equal to: 0
I is equal to: 1
I is equal to: 2
I is equal to: 3
I is equal to: 4


---------

In [92]:
import numpy as np

In [42]:
import pandas as pd

In [93]:
from numpy.random import randn

In [34]:
randn()

0.23600995355638402

In [88]:
answer=None
x=randn()
if x > 1:
    answer= 'GREATER THAN 1'
else:
    answer='UNSUCCESSFUL'
print(x)
print(answer)
  

1.5363742224976173
GREATER THAN 1


In [90]:
answer=None
x=randn()
if x > 1:
    answer= 'GREATER THAN 1'
elif x>=-1:
    answer='BETWEEN -1 and 1'
else:
    answer='LESS THAN -1'
print(x)
print(answer)

-1.119522958298378
LESS THAN -1


------

In [95]:
import numpy as np

In [96]:
from numpy.random import randn

In [179]:
N=100
counter=0
for i in randn(N):
    if (i>-1 and i<1):
        counter=counter+1
answer=counter/N
print(answer)
#print(counter)


0.72


------

In [182]:
A=list(range(100,201,10))

In [183]:
A

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

In [186]:
w=list(range(10))

In [187]:
w

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [188]:
w[5]

5

In [189]:
w[-4]

6

In [190]:
w[-4]=63

In [191]:
w

[0, 1, 2, 3, 4, 5, 63, 7, 8, 9]

In [192]:
len(w)

10

In [193]:
w[11]

IndexError: list index out of range

In [197]:
w=list(range(0,101,10))
w

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [198]:
w[2:5]

[20, 30, 40]

In [199]:
w[2:]

[20, 30, 40, 50, 60, 70, 80, 90, 100]

In [201]:
w[-2::-2]

[90, 70, 50, 30, 10]

In [202]:
w

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [204]:
X=np.array(w)

In [205]:
X

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [206]:
z=X[2:6]

In [207]:
z

array([20, 30, 40, 50])

In [208]:
z[2]=55

In [209]:
X

array([  0,  10,  20,  30,  55,  50,  60,  70,  80,  90, 100])

In [213]:
Z=X.copy()

In [214]:
Z

array([  0,  10,  20,  30,  55,  50,  60,  70,  80,  90, 100])

In [2]:
#[1,4,9,16,25,36,49]
#Concept of append in python
m=[]
for i in range(1,8):
    m.append(i**2)
print(m)

[1, 4, 9, 16, 25, 36, 49]


In [3]:
#List Comprehension
d=[i**2 for i in range(1,8)]
print(d)

[1, 4, 9, 16, 25, 36, 49]


In [8]:
#[49,36,25,16,9,4,1]

d1=[i**2 for i in range(-7,0)]
print(d1)

[49, 36, 25, 16, 9, 4, 1]


In [10]:
#[49,36,25,16,9,4,1]

n1=[]
for i in range(-7,0):
    n1.append(i**2)
print(n1)

[49, 36, 25, 16, 9, 4, 1]


In [11]:
#[49,36,25,16,9,4,1]

n1=[]
for i in range(7,0,-1):
    n1.append(i**2)
print(n1)

[49, 36, 25, 16, 9, 4, 1]


----------


In [12]:
#PANDAS DATAFRAME

In [20]:
import pandas as pd

In [21]:
df=pd.read_csv('P4_Demographic_Data')

FileNotFoundError: [Errno 2] File P4_Demographic_Data does not exist: 'P4_Demographic_Data'